files:
  
  - "local.properties.erb:local.properties"
  
  - "android/res/values/strings.xml.erb:android/res/values/strings.xml"
  - "android/src/AndroidLauncher.java.erb:android/src/AndroidLauncher.java"
  - "android/AndroidManifest.xml.erb:android/AndroidManifest.xml"
  
  - "core/src/core/MyGdxGame.java.erb:core/src/core/$(sketchName).java"
  - "core/src/MyGdxGame.gwt.xml.erb:core/src/$(sketchName).gwt.xml"
  
  - "desktop/src/desktop/DesktopLauncher.java.erb:desktop/src/desktop/DesktopLauncher.java"
  - "desktop/build.gradle.erb:desktop/build.gradle"
  
  - "desktop2/src/desktop/DesktopLauncher.java.erb:desktop2/src/desktop/DesktopLauncher.java"
  - "desktop2/src/desktop/Sync.java.erb:desktop2/src/desktop/Sync.java"
  - "desktop2/build.gradle.erb:desktop2/build.gradle"
  
  - "html/src/client/HtmlLauncher.java.erb:html/src/client/HtmlLauncher.java"
  - "html/src/GdxDefinition.gwt.xml.erb:html/src/GdxDefinition.gwt.xml"
  - "html/src/GdxDefinitionSuperdev.gwt.xml.erb:html/src/GdxDefinitionSuperdev.gwt.xml"
  - "html/build.gradle.erb:html/build.gradle"
  - "html/webapp/index.html.erb:html/webapp/index.html"
  
  
  
folders:
  - "core/src/core:core/src/$(packagePath)"
  - "android/src:android/src/$(packagePath)"
  - "desktop/src/desktop:desktop/src/$(packagePath)"
  - "desktop2/src/desktop:desktop2/src/$(packagePath)"
  - "html/src:html/src/$(packagePath)"
  - "html/src/client:html/src/$(packagePath)/client"
defaults:
  app: gdx-default-example
  sketch: DefaultExample
  package: net.mgsx.example